# Generated by Django 4.2.11 on 2024-04-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_rename_user_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_desp',
            new_name='review',
        ),
    ]
